version: '3.8'
services:
  db:
    build: .
    container_name: mybatis-demo-2023-6
    platform: linux/x86_64
    #    command: --default-authentication-plugin=mysql_native_password エラーが出たため修正
    command: mysqld --innodb_use_native_aio=0
    restart: always
    environment:
      environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      #      MYSQL_RßOOT_PASSWORD: password エラーが出てパスワードを初期化のため修正
      MYSQL_DATABASE: name_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
